export const products = [
    {
        id: 1,
        marca:'Chanel',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 4,
        precio: 1000,
        img: 'assets/img-banner1.webp',
    },
    {
        id: 2,
        marca:'Armani',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 7,
        precio: 1000,
        img: 'assets/img-banner2.webp',
    },
    {
        id: 3,
        marca:'Armani',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 0,
        precio: 1000,
        img: 'assets/img-banner3.webp',
    },
    {
        id: 4,
        marca:'Prada',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 10,
        precio: 1000,
        img: 'assets/img-banner4.webp',
    },
    {
        id: 5,
        marca:'Chanel',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 21,
        precio: 1000,
        img: 'assets/img-banner5.webp',
    },
    {
        id: 6,
        marca:'H&M',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 13,
        precio: 1000,
        img: 'assets/img-banner6.webp',
    },
    {
        id: 7,
        marca:'Chanel',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 0,
        precio: 1000,
        img: 'assets/img-banner7.webp',
    },
    {
        id: 8,
        marca:'IVY Moda',
        nombre: 'Dopo Designs Woolrich Klettersack Backpack',
        stock: 6,
        precio: 1000,
        img: 'assets/img-banner8.webp',
    }
];